### ISSUE TITLE
[Annoucement] WebListener 1.0.0-rc2 is now available on nuget.org

### ISSUE THREAD

**Issue by Tratcher** [aspnet/ServerTests#42]
The following packages have been released today on nuget.org:

Microsoft.AspNetCore.Server.WebListener.1.0.0-rc2-final
Microsoft.Net.Http.Server.1.0.0-rc2-final

WebListener is a Windows HTTP server built on the Http.Sys kernel mode driver. It exposes a number of Http.Sys features previously only availabe in IIS.

Kernel mode:
- Windows Authentication
- Port sharing
- HTTPS with SNI
- HTTP/2 over TLS (Windows 10)
- Direct file transmission
- Response caching

WebSockets (Windows 8)

WebListener is supported for edge deployments because it's built on the existing Http.Sys HTTP stack.  Note AspNetCoreModule is not compatible with WebListener for use behind IIS/Express, Kestrel must continue to be used in that scenario.

These packages are supported on Windows 7 and Windows Server 2008 R2 and later.

Usage with ASP.NET Core (Microsoft.AspNetCore.Server.WebListener):

```
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseWebListener(options =>
                {
                    options.ListenerSettings.Authentication.Schemes = AuthenticationSchemes.NTLM;
                    options.ListenerSettings.Authentication.AllowAnonymous = false;
                })
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
```

Direct usage (Microsoft.Net.Http.Server):

```
            var settings = new WebListenerSettings();
            settings.UrlPrefixes.Add("http://localhost:8080");

            using (WebListener listener = new WebListener(settings))
            {
                listener.Start();

                while (true)
                {
                    var context = await listener.AcceptAsync();
                    byte[] bytes = Encoding.ASCII.GetBytes("Hello World: " + DateTime.Now);
                    context.Response.ContentLength = bytes.Length;
                    context.Response.ContentType = "text/plain";

                    await context.Response.Body.WriteAsync(bytes, 0, bytes.Length);
                    context.Dispose();
                }
            }
```

**Comment by campersau** [comment]
Are there any public changelogs available for these packages?

**Comment by 304NotModified** [comment]
Could you tell us in which cases we should use this?

**Comment by Tratcher** [comment]
If you're on Windows and want to expose your server directly to the internet (Kestrel is not certified for direct exposure), or you need any of the features listed above.

**Comment by Tratcher** [comment]
@campersau not at the moment, though there is a prior announcement for API breaking changes. https://github.com/aspnet/ServerTests/issues/39

**Comment by zigzag95** [comment]
NTLM Authent not working:

![image](https://cloud.githubusercontent.com/assets/7827225/18585967/744bf1ca-7c1a-11e6-968a-447a79b02e6f.png)


`
 public static void Main(string[] args)
        {            

            var host = new WebHostBuilder()                
                 .UseWebListener(options =>
                 {
                     options.ListenerSettings.Authentication.Schemes = AuthenticationSchemes.NTLM;
                     options.ListenerSettings.Authentication.AllowAnonymous = false;                     

                 })
                 .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
`

**Comment by Tratcher** [comment]
You need to remove UseKestrel and UseIISIntegration and not run in IIS/Express, only self-host. See the comments above about AspNetCoreModule not being compatible with WebListener.

```
 public static void Main(string[] args)
{            
            var host = new WebHostBuilder()                
                 .UseWebListener(options =>
                 {
                     options.ListenerSettings.Authentication.Schemes = AuthenticationSchemes.NTLM;
                     options.ListenerSettings.Authentication.AllowAnonymous = false;                     

                 })
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseStartup<Startup>()
                .Build();

            host.Run();
}
```

**Comment by justdmitry** [comment]
> If you're on Windows and want to expose your server directly to the internet (Kestrel is not certified for direct exposure)

Where can I read more details about Kestrel, WebListener and other "expose to internet" certification?

**Comment by Tratcher** [comment]
@blowdart, do we have docs around edge certification?

**Comment by blowdart** [comment]
Considering there's no "expose to internet" certification, no, we don't.

**Comment by Tratcher** [comment]
@justdmitry @blowdart this is the official doc: https://docs.asp.net/en/latest/fundamentals/servers.html#kestrel

**Comment by Tratcher** [comment]
@justdmitry also https://github.com/aspnet/Docs/issues/1903

**Comment by NeelBhatt** [comment]
I have tried to convert it into blog post so that more people can know about this.

https://neelbhatt40.wordpress.com/2016/10/08/weblistener-is-now-on-nuget-a-net-core-server/

**Comment by tdykstra** [comment]
That blog post is well done, here's a proposed outline for the new doc that follows a similar organization and expands on it:

### What is WebListener
- Server for .NET Core
  - WebListener is a Windows HTTP server built on the Http.Sys kernel mode driver. It exposes a number of Http.Sys features previously only available in IIS. 
  - Built on Microsoft.Net.Http.Server which can be used independently outside of ASP.NET Core
- Features
  - Windows Authentication 
  - Port sharing
  - HTTPS with SNI
  - HTTP/2 over TLS (Windows 10)
  - Direct file transmission
  - Response caching
  - WebSockets (Windows 8)
- Supported Windows versions
  - Windows 7 and Windows Server 2008 R2 and later

### When to use it
- For use on Windows, when 
  - you want to expose the server directly to the internet and you don't want to use IIS, or 
  - you need any of the features listed above.

- Recommended for edge deployment because it's built on the existing Http.Sys HTTP stack.  Http.Sys is mature technology that protects against many kinds of attacks. Kestrel is newer, hasn't had a chance to develop as many protective features yet.

- Not compatible with ASP.NET Core Module, so can't be used with IIS even if you wanted to.

- Example scenario: Azure Service Fabric
  - can use Kestrel for internal microservice to microservice communications on private network (kestrel faster), should use WebListener for directly externally facing microservice layer.
  - if a cluster is not on a closed private virtual network, should use WebListener for the inter-service communication as they are open to other things contacting them on their "internal" ports.
  - For details link to SF docs
	
### How to use it in ASP.NET Core apps
	
- Install Microsoft.AspNetCore.Server.WebListener
	- Installs dependency Microsoft.Net.Http.Server 
- Main code
  - Remove UseKestrel and UseIISIntegration and add UseWebListener
  - Specify options in code, e.g. NTLM and AllowAnonymous
  - Code sample [here](https://github.com/aspnet/ServerTests/issues/42)
- Specify options in Http.sys registry keys
  - For configuring things such as timeouts
  - Some of these can be configured in-process but the defaults are in the registry
  - Link to https://support.microsoft.com/en-us/kb/820129
- Register prefixes so you don't have to run the app as admin
  - Get content from http://katanaproject.codeplex.com/wikipage?title=Selfhosting
- Set up SSL certificates
  - SSL setup out of process for WL, vs. in-process for Kestrel
  - Get content from http://katanaproject.codeplex.com/wikipage?title=Selfhosting
- Don't run in IIS
  - In VS the default launch profile is for IIS Express, but you can change it to the alternate console profile.

### How to use outside of ASP.NET Core

- Install Microsoft.Net.Http.Server NuGet package
- Code sample [here](https://github.com/aspnet/ServerTests/issues/42)

**Comment by NeelBhatt** [comment]
Thanks a lot @tdykstra.

 I will update my post by taking points from above comment.

**Comment by tdykstra** [comment]
Moving the doc outline to the Docs repo issue for this doc -- https://github.com/aspnet/Docs/issues/1827

**Comment by Tratcher** [comment]
WebListener 1.0.0 has now released to nuget.org. There are no significant changes from rc2.
